window.iconMap = {
             ambessa: "Ambessa",
            "aurelion sol": "AurelionSol",
            aurora: "Aurora",
            "cho'gat": "Chogath",
            "Dr.Mundo": "Dr.Mundo",
            hwei: "Hwei",
            "jarvan iv": "JarvanIV",
            "kai'sa": "Kaisa",
            "kha'zix": "Khazix",
            "kog'maw": "KogMaw",
            leBlanc: "LeBlanc",
            "lee sin": "LeeSin",
            "master yi": "MasterYi",
            mel: "Mel",
            "miss fortune": "MissFortune",
            "nunu y willump": "Nunu",
            "rek'sai": "RekSai",
            "renata glasc": "Renata",
            smolder: "Smolder",
            "tahm kench": "TahmKench",
            "twisted fate": "TwistedFate",
            "vel'koz": "Velkoz",
            wukong: "Wukong",
            yunara: "Yunara",
};